version: "3.7"

services:
  container:
    build: .
    working_dir: /container
    build:
      context: .
      args:
      - ANSIBLE_VAULT_PASSWORD
    environment:
    - TF_VAR_ssh_password
    - ANSIBLE_VAULT_PASSWORD
    - REGISTRY_PASSWORD
    volumes:
    - .:/container
    - .terraformrc:/root/.terraformrc
