version: "3.7"

services:
  controller:
    build: .
    working_dir: /baremetal-k8s
    environment:
    - ANSIBLE_VAULT_PASSWORD
    - REGISTRY_PASSWORD
    - KUBECONFIG=/baremetal-k8s/credentials/kubeconfig
    volumes:
    - ./.helm:/root/.helm
    - .:/baremetal-k8s

  dashboard:
    image: bitnami/kubectl:1.14.3
    environment:
    - KUBECONFIG=/baremetal-k8s/credentials/kubeconfig
    volumes:
    - .:/baremetal-k8s
    ports:
    - 9443:9443
    command: -n kube-system port-forward svc/kubernetes-dashboard 9443:443 --address=0.0.0.0

  grafana:
    image: bitnami/kubectl:1.14.3
    environment:
    - KUBECONFIG=/baremetal-k8s/credentials/kubeconfig
    volumes:
    - .:/baremetal-k8s
    ports:
    - 8088:8088
    command: -n monitoring port-forward svc/prometheus-operator-grafana 8088:80 --address=0.0.0.0
