version: "3.7"

services:
  container:
    build: .
    working_dir: /baremetal-k8s
    build:
      context: .
      args:
      - ANSIBLE_VAULT_PASSWORD
    environment:
    - ANSIBLE_VAULT_PASSWORD
    - REGISTRY_PASSWORD
    volumes:
    - .:/baremetal-k8s
    - .terraformrc:/root/.terraformrc
