---
- name: reset_calico_cni
  command: /bin/true
  notify:
    - delete 10-calico.conflist
    - delete calico-node containers

- name: delete 10-calico.conflist
  file:
    path: /etc/calico/10-calico.conflist
    state: absent

- name: delete calico-node containers
  shell: "docker ps -af name=k8s_POD_calico-node* -q | xargs --no-run-if-empty docker rm -f"
