apiVersion: v1
kind: Service
metadata:
  name: {{ template "railsgoat.fullname" . }}
  labels:
    app: {{ template "railsgoat.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "railsgoat.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.servicePort | int }}
      targetPort: {{ .Values.servicePort | int }}
