bases:
- _base.yaml

releases:
- name: namespaces
  namespace: kube-system
  labels:
    app: namespaces
  chart: incubator/raw
  version: 0.1.0
  values:
  - resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: fission

- name: metrics-server
  namespace: kube-system
  labels:
    app: metrics-server
  chart: stable/metrics-server
  version: 2.8.2
  values:
  - args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

- name: metallb
  namespace: kube-system
  chart: stable/metallb
  labels:
    app: metallb
  version: 0.9.6
  values:
  - configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.10.100-192.168.10.150

- name: prometheus-operator
  namespace: monitoring
  labels:
    app: prometheus-operator
  chart: stable/prometheus-operator
  version: 5.12.3
  values:
  - fullnameOverride: prometheus-operator

- name: rook
  namespace: kube-system
  labels:
    app: rook
  chart: rook-release/rook-ceph
  values:
  - flexVolumeDirPath: /var/lib/kubelet/volume-plugins
    image:
      prefix: rook
      repository: rook/ceph
      tag: master
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    rbacEnable: true
    pspEnable: true
