bases:
- ./defaults.yaml

releases:

- name: railsgoat
  installed: false
  namespace: dataplatform
  wait: true
  timeout: 600
  recreatePods: true
  labels:
    app: railsgoat
    group: dataplatform
  chart: ../charts/railsgoat
  values:
  - replicaCount: 1
    fullNameOverride: railsgoat
    image:
      repository: ilyasotkov/railsgoat
      tag: latest
      pullPolicy: Always
    serviceType: ClusterIP
    servicePort: 3000
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
      - railsgoat.cluster.home
    postgresql:
      persistence:
        enabled: true
        size: 4Gi

- name: presto
  installed: true
  namespace: dataplatform
  labels:
    app: presto
    group: dataplatform
  chart: ../charts/presto
  version: 0.1.1
  values:
  - kubernetesDNSDomain: baremetal-k8s
    server:
      workers: 1
      node:
        environment: production
        dataDir: /presto/etc/data
    config:
      path: /etc/presto
      http:
        port: 8080
      query:
        maxMemory: 2GB
        maxMemoryPerNode: 2GB
    jvm:
      maxHeapSize: 1G
      gcMethod:
        type: UseG1GC
        g1:
          heapRegionSize: 32M

- name: wordpress
  installed: false
  namespace: dataplatform
  timeout: 500
  labels:
    app: wordpress
    group: dataplatform
  chart: stable/wordpress
  version: 5.12.4
  values:
  - updateStrategy:
      type: Recreate
    mariadb:
      image:
        debug: true
      master:
        livenessProbe:
          initialDelaySeconds: 300
          failureThreshold: 30
        persistence:
          size: 30Gi
    livenessProbe:
      initialDelaySeconds: 600
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 20Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - name: wp.cluster.home

- name: suitecrm
  installed: true
  wait: true
  namespace: dataplatform
  timeout: 600
  labels:
    app: suitecrm
    group: dataplatform
  chart: ../charts/suitecrm
  version: 5.4.4
  values:
  - image:
      tag: 7.10.6-r8
    mariadb:
      image:
        debug: true
      master:
        livenessProbe:
          initialDelaySeconds: 300
          failureThreshold: 30
        persistence:
          size: 25Gi
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 25Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - name: suitecrm.cluster.home
