bases:
- ./defaults.yaml

releases:

- name: es-operator
  installed: false
  namespace: logging
  labels:
    app: es-operator
  chart: akomljen-charts/elasticsearch-operator
  values: []

- name: efk
  installed: false
  namespace: logging
  labels:
    app: efk
  chart: akomljen-charts/efk
  values:
  - kibana:
      ingress:
        enabled: true
        hosts:
        - kibana.cluster.home
        annotations:
          kubernetes.io/ingress.class: nginx
    elasticsearch:
      spec:
        client-java-options: -Xms128m -Xmx128m
        master-java-options: -Xms512m -Xmx512m
        data-java-options: -Xms512m -Xmx512m
        data-volume-size: 7Gi
        storage:
          type: rook-ceph-block
        resources:
          requests:
            memory: 1024Mi
            cpu: 200m
          limits:
            memory: 1536Mi
            cpu: 750m
