bases:
- ./defaults.yaml

releases:

- name: rook-ceph-operator
  installed: true
  namespace: rook-ceph
  labels:
    app: rook-ceph-operator
  chart: rook-release/rook-ceph
  values:
  - agent:
      flexVolumeDirPath: /var/lib/kubelet/volume-plugins
    image:
      prefix: rook
      repository: rook/ceph
      tag: master
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    rbacEnable: true
    pspEnable: true
    logLevel: WARNING

- name: rook-ceph-cluster
  installed: true
  recreatePods: true
  namespace: rook-ceph
  labels:
    app: rook-ceph-cluster
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: rook-ceph
      spec:
        cephVersion:
          image: ceph/ceph:v13.2.6-20190604
        dataDirHostPath: /var/lib/rook
        mon:
          count: 3
          allowMultiplePerNode: true
        dashboard:
          enabled: false
        storage:
          useAllNodes: false
          useAllDevices: false
          config:
            databaseSizeMB: "1024"
            journalSizeMB: "1024"
          nodes:
          - name: node01
            location: rack=rack1
            devices:
            # - name: sda
            - name: sdc
          # - name: master-node
          #   location: rack=rack1
          #   devices:
          #   - name: sda
          # - name: node00
          #   location: rack=rack1
          #   devices:
          #   - name: sda

- name: rook-ceph-storage
  installed: true
  namespace: rook-ceph
  labels:
    app: rook-ceph-storage
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: ceph.rook.io/v1
      kind: CephBlockPool
      metadata:
        name: replicapool
      spec:
        failureDomain: host
        replicated:
          size: 3
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: gp
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: ceph.rook.io/block
      parameters:
        blockPool: replicapool
        clusterNamespace: rook-ceph

- name: rook-ceph-test
  installed: false
  namespace: rook-ceph
  labels:
    app: rook-ceph-test
  chart: incubator/raw
  version: 0.2.3
  wait: false
  values:
  - resources:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: rook-ceph-test-lg
      spec:
        storageClassName: gp
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
