---
dependencies:
  - role: container-engine/cri-o
    when:
      - container_manager == 'crio'
    tags:
      - container-engine
      - crio

  - role: container-engine/docker
    when:
      - container_manager == 'docker'
    tags:
      - container-engine
      - docker
