---
- name: restart calico-rr
  command: /bin/true
  notify:
    - Calico-rr | reload systemd
    - Calico-rr | reload calico-rr

- name: Calico-rr | reload systemd
  systemd:
    daemon_reload: true

- name: Calico-rr | reload calico-rr
  service:
    name: calico-rr
    state: restarted
